export const initialFormState = {
  name: "",
  telephone: "",
  petName: "",
  petSpecies: "",
  petBreed: "",
  petAge: "",
  petSize: "",
  clienteId: "",
  petId: "",
  servicoId: "",
  valorCobrado: "",
  dataAtendimento: "",
  horarioAtendimento: "",
  pulgas: "",
  carrapatos: "",
  temperamentos: "",
  alergias: "",
  doencas: "",
  servicosDisponiveis: "",
  notas: "",
};
