-- CreateTable
CREATE TABLE "ATENDIMENTOS" (
    "ID_ATENDIMENTO" SERIAL NOT NULL,
    "ID_CLIENTE" INTEGER NOT NULL,
    "ID_PET" INTEGER NOT NULL,
    "ID_SERVICO" INTEGER NOT NULL,
    "VALOR_COBRADO" DECIMAL(65,30) NOT NULL,
    "TIPO" VARCHAR(50) NOT NULL,
    "NOTAS" TEXT,
    "PUBLIC_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "VERSION" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "ATENDIMENTOS_pkey" PRIMARY KEY ("ID_ATENDIMENTO")
);

-- CreateTable
CREATE TABLE "ATENDIMENTO_IMAGENS" (
    "ID_IMAGEM" SERIAL NOT NULL,
    "ID_ATENDIMENTO" INTEGER NOT NULL,
    "CAMINHO_IMAGEM" VARCHAR(255) NOT NULL,
    "DATA_UPLOAD" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "PUBLIC_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "VERSION" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "ATENDIMENTO_IMAGENS_pkey" PRIMARY KEY ("ID_IMAGEM")
);

-- CreateTable
CREATE TABLE "CLIENTES" (
    "ID_CLIENTE" SERIAL NOT NULL,
    "NOME" VARCHAR(100) NOT NULL,
    "TELEFONE" VARCHAR(20) NOT NULL,
    "ENDERECO" VARCHAR(255) NOT NULL,
    "PUBLIC_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "VERSION" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "CLIENTES_pkey" PRIMARY KEY ("ID_CLIENTE")
);

-- CreateTable
CREATE TABLE "PETS" (
    "ID_PET" SERIAL NOT NULL,
    "NOME" TEXT NOT NULL,
    "RACA" TEXT,
    "DATA_NASC" TIMESTAMP(3),
    "ID_CLIENTE" INTEGER NOT NULL,
    "PUBLIC_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "VERSION" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "PETS_pkey" PRIMARY KEY ("ID_PET")
);

-- CreateTable
CREATE TABLE "PACOTES" (
    "ID_ASSINATURA" SERIAL NOT NULL,
    "ID_CLIENTE" INTEGER NOT NULL,
    "ID_SERVICO" INTEGER NOT NULL,
    "QTD_BANHOS" INTEGER NOT NULL DEFAULT 0,
    "PUBLIC_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "VERSION" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "PACOTES_pkey" PRIMARY KEY ("ID_ASSINATURA")
);

-- CreateTable
CREATE TABLE "SERVICOS" (
    "ID_SERVICO" SERIAL NOT NULL,
    "NOME" VARCHAR(100) NOT NULL,
    "DESCRICAO" TEXT,
    "VALOR" DECIMAL(65,30) NOT NULL,
    "PUBLIC_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "VERSION" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "SERVICOS_pkey" PRIMARY KEY ("ID_SERVICO")
);

-- CreateTable
CREATE TABLE "USUARIOS" (
    "ID_USUARIO" SERIAL NOT NULL,
    "NOME" VARCHAR(100) NOT NULL,
    "DESCRICAO" TEXT,
    "SENHA_HASH" VARCHAR(255) NOT NULL,
    "PUBLIC_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "VERSION" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "USUARIOS_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- CreateIndex
CREATE UNIQUE INDEX "ATENDIMENTOS_PUBLIC_ID_key" ON "ATENDIMENTOS"("PUBLIC_ID");

-- CreateIndex
CREATE INDEX "ATENDIMENTOS_UPDATED_AT_idx" ON "ATENDIMENTOS"("UPDATED_AT");

-- CreateIndex
CREATE UNIQUE INDEX "ATENDIMENTO_IMAGENS_PUBLIC_ID_key" ON "ATENDIMENTO_IMAGENS"("PUBLIC_ID");

-- CreateIndex
CREATE INDEX "ATENDIMENTO_IMAGENS_UPDATED_AT_idx" ON "ATENDIMENTO_IMAGENS"("UPDATED_AT");

-- CreateIndex
CREATE UNIQUE INDEX "CLIENTES_PUBLIC_ID_key" ON "CLIENTES"("PUBLIC_ID");

-- CreateIndex
CREATE INDEX "CLIENTES_UPDATED_AT_idx" ON "CLIENTES"("UPDATED_AT");

-- CreateIndex
CREATE UNIQUE INDEX "PETS_PUBLIC_ID_key" ON "PETS"("PUBLIC_ID");

-- CreateIndex
CREATE INDEX "PETS_UPDATED_AT_idx" ON "PETS"("UPDATED_AT");

-- CreateIndex
CREATE UNIQUE INDEX "PACOTES_PUBLIC_ID_key" ON "PACOTES"("PUBLIC_ID");

-- CreateIndex
CREATE INDEX "PACOTES_UPDATED_AT_idx" ON "PACOTES"("UPDATED_AT");

-- CreateIndex
CREATE UNIQUE INDEX "SERVICOS_PUBLIC_ID_key" ON "SERVICOS"("PUBLIC_ID");

-- CreateIndex
CREATE INDEX "SERVICOS_UPDATED_AT_idx" ON "SERVICOS"("UPDATED_AT");

-- CreateIndex
CREATE UNIQUE INDEX "USUARIOS_PUBLIC_ID_key" ON "USUARIOS"("PUBLIC_ID");

-- CreateIndex
CREATE INDEX "USUARIOS_UPDATED_AT_idx" ON "USUARIOS"("UPDATED_AT");

-- AddForeignKey
ALTER TABLE "ATENDIMENTOS" ADD CONSTRAINT "ATENDIMENTOS_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "CLIENTES"("ID_CLIENTE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ATENDIMENTOS" ADD CONSTRAINT "ATENDIMENTOS_ID_PET_fkey" FOREIGN KEY ("ID_PET") REFERENCES "PETS"("ID_PET") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ATENDIMENTOS" ADD CONSTRAINT "ATENDIMENTOS_ID_SERVICO_fkey" FOREIGN KEY ("ID_SERVICO") REFERENCES "SERVICOS"("ID_SERVICO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ATENDIMENTO_IMAGENS" ADD CONSTRAINT "ATENDIMENTO_IMAGENS_ID_ATENDIMENTO_fkey" FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "ATENDIMENTOS"("ID_ATENDIMENTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PETS" ADD CONSTRAINT "PETS_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "CLIENTES"("ID_CLIENTE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PACOTES" ADD CONSTRAINT "PACOTES_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "CLIENTES"("ID_CLIENTE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PACOTES" ADD CONSTRAINT "PACOTES_ID_SERVICO_fkey" FOREIGN KEY ("ID_SERVICO") REFERENCES "SERVICOS"("ID_SERVICO") ON DELETE RESTRICT ON UPDATE CASCADE;
