-- AlterTable
ALTER TABLE "ATENDIMENTOS" ADD COLUMN     "IDADE_PET" VARCHAR(20),
ADD COLUMN     "NOME_DONO" VARCHAR(100),
ADD COLUMN     "NOME_PET" VARCHAR(100),
ADD COLUMN     "PORTE_PET" VARCHAR(20),
ADD COLUMN     "RACA_PET" VARCHAR(100),
ADD COLUMN     "TELEFONE_DONO" VARCHAR(20);
