import { Injectable, NotFoundException } from '@nestjs/common';
import * as bcrypt from 'bcryptjs';
import { PrismaService } from '../prisma/prisma.service';
import { CreateUsuarioDto } from './dto/create-usuario.dto';
import { UpdateUsuarioDto } from './dto/update-usuario.dto';
import { UsuarioSyncBatchRequestDto, UsuarioSyncItemDto } from './dto/usuario-sync.dto';

@Injectable()
export class UsuariosService {
  constructor(private prisma: PrismaService) {}

  async findByNome(nome: string) {
    return this.prisma.uSUARIOS.findFirst({
      where: { NOME: nome },
    });
  }

  async login(nome: string, senha: string): Promise<{ token: string }> {
    const usuario = await this.findByNome(nome);
    if (!usuario) throw new NotFoundException('Usuário não encontrado');
    const senhaValida = await bcrypt.compare(senha, usuario.SENHA_HASH);
    if (!senhaValida) throw new NotFoundException('Senha inválida');
    const jwt = require('jsonwebtoken');
    const token = jwt.sign(
      { id: usuario.ID_USUARIO },
      process.env.JWT_SECRET || 'secret',
      { expiresIn: '1d' },
    );
    return { token };
  }

  async create(createUsuarioDto: CreateUsuarioDto) {
    const senhaHash = await bcrypt.hash(createUsuarioDto.SENHA, 10);
    const { SENHA, ...rest } = createUsuarioDto;
    return this.prisma.uSUARIOS.create({
      data: {
        ...rest,
        SENHA_HASH: senhaHash,
      },
    });
  }

  async findAll() {
    return this.prisma.uSUARIOS.findMany();
  }

  // --- Offline-first sync logic ---
  public async getChanges(since?: string) {
    const sinceDate = since ? new Date(since) : new Date(0);
    return this.prisma.uSUARIOS.findMany({
      where: {
        OR: [
          { UPDATED_AT: { gt: sinceDate } },
          { DELETED_AT: { gte: sinceDate } },
        ],
      },
      orderBy: { UPDATED_AT: 'asc' },
    });
  }

  public async batchUpsert(body: UsuarioSyncBatchRequestDto) {
    const results = [] as Array<{ publicId: string; status: 'applied' | 'conflict' | 'skipped'; server?: any }>;

    for (const item of body.items) {
      const res = await this.applyOne(item);
      results.push(res);
    }

    return { results };
  }

  private async applyOne(item: UsuarioSyncItemDto): Promise<{ publicId: string; status: 'applied' | 'conflict' | 'skipped'; server?: any }> {
    const { PUBLIC_ID, UPDATED_AT, VERSION, DELETED_AT, NOME, DESCRICAO, SENHA_HASH } = item;

    if (!PUBLIC_ID) {
      // create new (PUBLIC_ID generated by default)
      const created = await this.prisma.uSUARIOS.create({
        data: {
          NOME: NOME ?? 'Sem nome',
          DESCRICAO: DESCRICAO ?? null,
          SENHA_HASH: SENHA_HASH ?? '',
          // UPDATED_AT auto; CREATED_AT auto; PUBLIC_ID auto
          DELETED_AT: DELETED_AT ? new Date(DELETED_AT) : null,
        },
      });
      return { publicId: created.PUBLIC_ID, status: 'applied' };
    }

    const existing = await this.prisma.uSUARIOS.findUnique({ where: { PUBLIC_ID } });
    if (!existing) {
      // create with provided PUBLIC_ID (if client generated)
      const created = await this.prisma.uSUARIOS.create({
        data: {
          PUBLIC_ID,
          NOME: NOME ?? 'Sem nome',
          DESCRICAO: DESCRICAO ?? null,
          SENHA_HASH: SENHA_HASH ?? '',
          DELETED_AT: DELETED_AT ? new Date(DELETED_AT) : null,
        },
      });
      return { publicId: created.PUBLIC_ID, status: 'applied' };
    }

    // Conflict detection: last-writer-wins by UPDATED_AT
    const incomingUpdated = UPDATED_AT ? new Date(UPDATED_AT) : undefined;
    if (incomingUpdated && incomingUpdated > existing.UPDATED_AT) {
      const updated = await this.prisma.uSUARIOS.update({
        where: { PUBLIC_ID },
        data: {
          NOME: NOME ?? existing.NOME,
          DESCRICAO: typeof DESCRICAO !== 'undefined' ? DESCRICAO : existing.DESCRICAO,
          SENHA_HASH: typeof SENHA_HASH !== 'undefined' ? SENHA_HASH : existing.SENHA_HASH,
          DELETED_AT: typeof DELETED_AT !== 'undefined' ? (DELETED_AT ? new Date(DELETED_AT) : null) : existing.DELETED_AT,
          VERSION: { increment: 1 },
        },
      });
      return { publicId: updated.PUBLIC_ID, status: 'applied' };
    }

    // If incoming has no UPDATED_AT (legacy client) but fields present, accept update
    if (!incomingUpdated && (NOME !== undefined || DESCRICAO !== undefined || SENHA_HASH !== undefined || typeof DELETED_AT !== 'undefined')) {
      const updated = await this.prisma.uSUARIOS.update({
        where: { PUBLIC_ID },
        data: {
          NOME: NOME ?? existing.NOME,
          DESCRICAO: typeof DESCRICAO !== 'undefined' ? DESCRICAO : existing.DESCRICAO,
          SENHA_HASH: typeof SENHA_HASH !== 'undefined' ? SENHA_HASH : existing.SENHA_HASH,
          DELETED_AT: typeof DELETED_AT !== 'undefined' ? (DELETED_AT ? new Date(DELETED_AT) : null) : existing.DELETED_AT,
          VERSION: { increment: 1 },
        },
      });
      return { publicId: existing.PUBLIC_ID, status: 'applied' };
    }

    // stale write
    return { publicId: existing.PUBLIC_ID, status: 'conflict', server: existing };
  }

  async softDeleteByPublicId(publicId: string) {
    const existing = await this.prisma.uSUARIOS.findUnique({ where: { PUBLIC_ID: publicId } });
    if (!existing) throw new NotFoundException(`Usuário com PUBLIC_ID ${publicId} não encontrado`);
    return this.prisma.uSUARIOS.update({
      where: { PUBLIC_ID: publicId },
      data: { DELETED_AT: new Date(), VERSION: { increment: 1 } },
    });
  }
}
