-- AlterTable
ALTER TABLE "CLIENTES" ADD COLUMN     "FOTO_USUARIO" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "USUARIOS" ADD COLUMN     "FOTO" VARCHAR(255),
ADD COLUMN     "TIPOS" TEXT[] DEFAULT ARRAY[]::TEXT[];
